spring:
  #### redis连接配置 ############################################
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 10
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    timeout: 1000ms