rocketmq:
  name-server: localhost:9876
  producer:
    group: rocketmq-app-box
    send-message-timeout: 30000
    retry-next-server: true
    retry-times-when-send-async-failed: 2

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://139.9.93.229:3306/test?useSSL=false&serverTimezone=GMT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver